### ISSUE TITLE
[SETTING]

### ISSUE THREAD

**Issue by 0seo8** [KDT-Final-Project/Front#3]
# ISSUS: ✅ SETTING
---

## Description
---
커밋 룰 등 기본 세팅 논의하기

## Todo
---
- [ ]  react 컴포넌트 구조 어떻게 짤 건지?
-  [ ]  라이브러리 통일
-  [ ]  변수 스타일 / 코딩 스타일 / 커밋 룰
 - [ ]   git code 관리 어떻게 할지?

## ETC
---
기타사항
